apiVersion: v1
kind: Deployment
metadata:
  name: ${project.artifactId}
  labels:
    application: das-service
spec:
  template:
    spec:
      containers:
        - env:
            - name: "AB_OFF"
              value: "true"
            - name: "AB_JOLOKIA_OFF"
              value: "true"
            - name: DB_USERNAME
              valueFrom:
                 secretKeyRef:
                   name: postgresql
                   key: database-user
            - name: DB_PASSWORD
              valueFrom:
                 secretKeyRef:
                   name: postgresql
                   key: database-password
            - name: DATABASE_NAME
              valueFrom:
                 secretKeyRef:
                   name: postgresql
                   key: database-name
            - name: JAVA_OPTIONS
              value: "-Dswarm.datasources.data-sources.MyDS.connection-url=jdbc:postgresql://postgresql:5432/$(DATABASE_NAME) 
                      -Dswarm.datasources.data-sources.MyDS.user-name=$(DB_USERNAME) 
                      -Dswarm.datasources.data-sources.MyDS.password=$(DB_PASSWORD) 
                      -Dswarm.datasources.data-sources.MyDS.driver-name=postgresql
                      -DAB_JOLOKIA_OFF=true"
                                         
