apiVersion: v1
kind: Service
metadata:
  name: ${project.artifactId}-odata
spec:
  ports:
  - name: ${project.artifactId}-jdbc
    port: 8080
    targetPort: 8080
  selector:
    app: ${project.artifactId}
